spring:
  profiles: dev
  datasource:
   url: jdbc:h2:mem:agentdb
   username: sa
   password: password
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   show-sql: true
  hibernate:
   # Hibernate ddl auto (create, create-drop, validate, update)
   ddl-auto: create
  h2:
    console:
      enabled: true
server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-887734.okta.com/oauth2/default
    client-id: 0oa1s0lajyxlbMcwr357